school_data/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from college.views import CreateCollegeView
from school.views import CreateSchoolView, excelFile
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', CreateSchoolView.as_view(), name='home'),
    url(r'^college/$', CreateCollegeView.as_view(), name='college'),
    url(r'^excel/$', excelFile),
    # url(r'^school_data/', include('school_data.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

college/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.forms import ModelForm



ACCREDITED_CHOICES = (
    ('1', 'Yes'),
    ('0', 'No'),
)

STATE_CHOICES = (
      ('AP' , 'Andhra Pradesh'), (
      'AR' , 'Arunachal Pradesh'), (
      'AS' , 'Assam'), (
      'BR' , 'Bihar'), (
      'CT' , 'Chhattisgarh'), (
      'GA' , 'Goa'), (
      'GJ' , 'Gujarat'), (
      'HR' , 'Haryana'), (
      'HP' , 'Himachal Pradesh'), (
      'JK' , 'Jammu & Kashmir'), (
      'JH' , 'Jharkhand'), (
      'KA' , 'Karnataka'), (
      'KL' , 'Kerala'), (
      'MP' , 'Madhya Pradesh'), (
      'MH' , 'Maharashtra'), (
      'MN' , 'Manipur'), (
      'ML' , 'Meghalaya'), (
      'MZ' , 'Mizoram'), (
      'NL' , 'Nagaland'), (
      'OR' , 'Odisha'), (
      'PB' , 'Punjab'), (
      'RJ' , 'Rajasthan'), (
      'SK' , 'Sikkim'), (
      'TN' , 'Tamil Nadu'), (
      'TG' , 'Telangana'), (
      'TR' , 'Tripura'), (
      'UK' , 'Uttarakhand'), (
      'UP' , 'Uttar Pradesh'), (
      'WB' , 'West Bengal'), (
      'AN' , 'Andaman & Nicobar'), (
      'CH' , 'Chandigarh'),
      ('DN' , 'Dadra and Nagar Haveli'),
      ('DD' , 'Daman & Diu'),
      ('DL' , 'Delhi'),
      ('LD' , 'Lakshadweep'),
      ('PY' , 'Puducherry'),
)

LOCATION_CHOICES = (
    ('City', 'A city'),
    ('Town', 'A town'),
    ('CO', 'Outskirts of a city'),
    ('TO', 'Outskirts of a town'),
    ('NUA', 'A non urban area'),
)


class Leadership (models.Model):
    name_company = models.CharField(max_length=100)
    name_founder = models.CharField(max_length=40)
    year_trust = models.IntegerField(max_length=4)
    month_college = models.CharField(max_length=10)
    year_college = models.IntegerField(max_length=4)


class Recognition(models.Model):
    course_name = models.CharField(max_length=100)
    type_approval = models.CharField(max_length=100)
    easyness = models.TextField()
    criteria = models.TextField()

class Accreditation(models.Model):
    year_rating = models.IntegerField(max_length=4)
    rating = models.CharField(max_length=10)
    rating_body = models.CharField(max_length=100)

class Award(models.Model):
    name_award = models.CharField(max_length=100)
    awarding_body = models.CharField(max_length=100)
    year_award = models.IntegerField(max_length=4)


class College(models.Model):
    name = models.CharField("College Name", max_length=100)
    street_address_1 = models.CharField(max_length=100, blank=True, null=True)
    street_address_2 = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True, choices=STATE_CHOICES)
    pincode = models.IntegerField(max_length=6, null=True, blank=True)
    latitude = models.DecimalField(max_digits=31, decimal_places=28, null=True, blank=True,
                                   validators=[MaxValueValidator(90), MinValueValidator(-90)])
    longitude = models.DecimalField(max_digits=32, decimal_places=28, null=True, blank=True,
                                    validators=[MaxValueValidator(180), MinValueValidator(-180)])
    image = models.ImageField("College Photo", upload_to='college', null=True, blank=True)
    email = models.EmailField()
    telephone = models.CharField(max_length=12)
    principal_name = models.CharField(max_length=40)
    principal_number = models.CharField(max_length=12)
    respondent_name = models.CharField(max_length=40)
    respondent_designation = models.CharField(max_length=40)
    location = models.CharField(max_length=10, choices=LOCATION_CHOICES)
    leaderships = models.ManyToManyField(Leadership)
    recognition = models.ManyToManyField(Recognition)
    college_accreditated = models.CharField("Is College Accredited", max_length=10, choices=ACCREDITED_CHOICES)
    accreditations = models.ManyToManyField(Accreditation)
    awards = models.ManyToManyField(Award)
    campus_size = models.CharField("Campus Size", max_length=20)
    builtup_area = models.CharField("Built-Up Area", max_length=20)
    distance_railway = models.CharField("Distance to nearest Railway Station", max_length=20)
    distance_bus = models.CharField("Distance to nearest Bust Stop", max_length=20)
    number_labs = models.IntegerField("Number of Labs", max_length=3)
    boys_hostel = models.FloatField("% Boys having Hostel Facility", max_length=5)
    girls_hostel = models.FloatField("% Girls having Hostel Facility", max_length=5)
    playground = models.CharField(max_length=10, choices=ACCREDITED_CHOICES)
    number_sport_centers = models.IntegerField("Number of Sport Centres in College", max_length=3)
    transport_facility = models.CharField("Availability of Transport Facility", max_length=10, choices=ACCREDITED_CHOICES)
    number_buses = models.IntegerField("Number of Buses", max_length=3)
    number_mini_buses = models.IntegerField("Number of Mini-Buses", max_length=3)
    def __str__(self):              # __unicode__ on Python 2
        return self.name

class CollegeForm(ModelForm):
    class Meta:
        model = College

school/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.forms import ModelForm

CLASS_CHOICES = (
    ('0', 'Pre-School'),            
    ('1', 'First'),
    ('2', 'Second'),
    ('3', 'Third'),
    ('4', 'Fourth'),
    ('5', 'Fifth'),
    ('6', 'Sixth'),
    ('7', 'Seventh'),
    ('8', 'Eighth'),
    ('9', 'Nineth'),
    ('10', 'Tenth'),
    ('11', 'Eleventh'),
    ('12', 'Twelth'),
)

RECOGNIZED_CHOICES = (
    ('1', 'Yes'),
    ('0', 'No'),
)
TYPE_CHOICES = (
    ('Private aided by government', 'Private Aided by Government'),
    ('Private Unaided', 'Private Unaided'),
    ('Government', 'Government'),
    ('Religious', 'Religious'),
    ('Special School', 'Special Needs School'),
)
LANGUAGE_CHOICES = (
    ('English','English'),
    ('Hindi','Hindi'),
    ('Mix English and Hindi','Mix English and Hindi'),
    ('Urdu','Urdu'),
    ('Gujarati','Gujarati'),
    ('Tamil','Tamil'),
    ('Telugu','Telugu'),
    ('Kannad','Kannad'),
    ('Punjabi','Punjabi'),
    ('Malayalam','Malayalam'),
    ('Marathi','Marathi'),
    ('Bengali','Bengali'),
    ('Oriya','Oriya'),
    ('Assamese','Assamese'),
    ('Other','Other'),
)

STATE_CHOICES = (
      ('AP' , 'Andhra Pradesh'), (
      'AR' , 'Arunachal Pradesh'), (
      'AS' , 'Assam'), (
      'BR' , 'Bihar'), (
      'CT' , 'Chhattisgarh'), (
      'GA' , 'Goa'), (
      'GJ' , 'Gujarat'), (
      'HR' , 'Haryana'), (
      'HP' , 'Himachal Pradesh'), (
      'JK' , 'Jammu & Kashmir'), (
      'JH' , 'Jharkhand'), (
      'KA' , 'Karnataka'), (
      'KL' , 'Kerala'), (
      'MP' , 'Madhya Pradesh'), (
      'MH' , 'Maharashtra'), (
      'MN' , 'Manipur'), (
      'ML' , 'Meghalaya'), (
      'MZ' , 'Mizoram'), (
      'NL' , 'Nagaland'), (
      'OR' , 'Odisha'), (
      'PB' , 'Punjab'), (
      'RJ' , 'Rajasthan'), (
      'SK' , 'Sikkim'), (
      'TN' , 'Tamil Nadu'), (
      'TG' , 'Telangana'), (
      'TR' , 'Tripura'), (
      'UK' , 'Uttarakhand'), (
      'UP' , 'Uttar Pradesh'), (
      'WB' , 'West Bengal'), (
      'AN' , 'Andaman & Nicobar'), (
      'CH' , 'Chandigarh'),
      ('DN' , 'Dadra and Nagar Haveli'),
      ('DD' , 'Daman & Diu'),
      ('DL' , 'Delhi'),
      ('LD' , 'Lakshadweep'),
      ('PY' , 'Puducherry'),
)

class School(models.Model):
    name = models.CharField("School Name*", max_length=100)
    lowest_class = models.CharField("Lowest Class*", max_length=10, choices=CLASS_CHOICES)
    highest_class = models.CharField("Highest Class*", max_length=10, choices=CLASS_CHOICES)
    recognized = models.CharField("Recognized ?*", max_length=10, choices=RECOGNIZED_CHOICES)
    management_type = models.CharField("Management Type*", max_length=100, choices=TYPE_CHOICES, help_text="Select Management Type")
    teacher_strength = models.IntegerField("Teacher Strength", max_length=10, blank=True, null=True, help_text='Enter only numbers without comma')
    student_strength = models.IntegerField("Student Strength", max_length=10, blank=True, null=True, help_text='Enter only numbers without comma')
    medium_of_instruction = models.CharField("Medium of Instruction*", max_length=100, choices=LANGUAGE_CHOICES)
    other_language = models.CharField("Other Language", max_length=20, null=True, blank=True)
    min_fee = models.IntegerField("Minimum Monthly Fee", max_length=6, null=True, blank=True, help_text="Enter only numbers without comma or rupee symbol")
    max_fee = models.IntegerField("Maximum Monthly Fee", max_length=6, null=True, blank=True, help_text="Enter only numbers without comma or rupee symbol")
    establishment = models.IntegerField("Year of Establishment* (YYYY)", max_length=4)
    recognition = models.IntegerField("Year of Recognition* (YYYY)", max_length=4)
    image = models.ImageField("School Photo", upload_to='school', null=True, blank=True)
    street_address_1 = models.CharField("Street Address 1", max_length=100, blank=True, null=True)
    street_address_2 = models.CharField("Street Address 2", max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True, choices=STATE_CHOICES, help_text='Select State')
    pincode = models.IntegerField(max_length=6, null=True, blank=True)
    email = models.EmailField("E-Mail", null=True, blank=True)
    phone_number = models.IntegerField("Phone Number", max_length=12, null=True, blank=True, help_text='STD code- phone number/ Mobile number')
    latitude = models.DecimalField(max_digits=31, decimal_places=28, null=True, blank=True,
                                   validators=[MaxValueValidator(90), MinValueValidator(-90)])
    longitude = models.DecimalField(max_digits=32, decimal_places=28, null=True, blank=True,
                                    validators=[MaxValueValidator(180), MinValueValidator(-180)])
    

    def __str__(self):              # __unicode__ on Python 2
        return self.name
    class Meta:
        unique_together = ('name', 'street_address_1', 'street_address_2', 'pincode')

class SchoolForm(ModelForm):
    class Meta:
        model = School

college/views.py
from django.views.generic import CreateView

from models import Award, College, CollegeForm

from school_data.settings import MEDIA_URL
from django.http import HttpResponse
import simplejson
import json
import csv

from school_data.settings import PROJECT_PATH

def response_mimetype(request):
    if "application/json" in request.META['HTTP_ACCEPT']:
        return "application/json"
    else:
        return "text/plain"

class CreateCollegeView(CreateView):
    model = College
    template_name = 'college.html'
    form_class = CollegeForm
    
    def form_valid(self, form):
        self.object = form.save()
        f = self.request.FILES.get('image')
        if f:
            data = [{'name': f.name, 'url': MEDIA_URL + "college/" + f.name.replace(" ", "_")}]
        response = JSONResponse("Thank You For Filling the Form", {}, response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response


class JSONResponse(HttpResponse):
    """JSON response class."""
    def __init__(self,obj='',json_opts={},mimetype="application/json",*args,**kwargs):
        content = simplejson.dumps(obj,**json_opts)
        super(JSONResponse,self).__init__(content,mimetype,*args,**kwargs)

school/views.py
from django.views.generic import CreateView

from models import School, SchoolForm

from school_data.settings import MEDIA_URL
from django.http import HttpResponse
import simplejson
import json
import csv

from school_data.settings import PROJECT_PATH

def response_mimetype(request):
    if "application/json" in request.META['HTTP_ACCEPT']:
        return "application/json"
    else:
        return "text/plain"

class CreateSchoolView(CreateView):
    model = School
    template_name = 'school.html'
    #form_class = SchoolForm
    
    def form_valid(self, form):
        self.object = form.save()
        f = self.request.FILES.get('image')
        if f:
            data = [{'name': f.name, 'url': MEDIA_URL + "school/" + f.name.replace(" ", "_")}]
        response = JSONResponse("Thank You For Filling the Form", {}, response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response


class JSONResponse(HttpResponse):
    """JSON response class."""
    def __init__(self,obj='',json_opts={},mimetype="application/json",*args,**kwargs):
        content = simplejson.dumps(obj,**json_opts)
        super(JSONResponse,self).__init__(content,mimetype,*args,**kwargs)


def excelFile(request):
    array = []
    filepath = PROJECT_PATH + '/static/patna_school_list.csv'
    csvfile = open(filepath, 'rb')
    file_data = csv.reader(csvfile)
    print type(file_data)
    for row in file_data:
        array.append(row)
    

    data = json.dumps({"data" : array})
    return HttpResponse(data)

school_data/templates/college.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>IndiaI-Add School</title>

    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.0/css/jquery.dataTables.css">

    <!-- Custom styles for this template -->
    <style type="text/css">
        
        html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
      html, body, .container { height: 100% }

    </style>
    
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://www.indiai.org" target="_blank">
          <img style="width:140px; margin-top:-15px;" src="https://s3-us-west-2.amazonaws.com/indiai/map+my+logo.png"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a  title="$.scrollTo( '#school', 1800, {easing:'elasout'} );" href="#school" id="add-school" >Add School</a></li>
            <li ><a title="$.scrollTo( '#mapmyschool-desc', 1800, {easing:'elasout'} );" href="#mapmyschool-desc" id="project" >Campaign</a></li>
            <li ><a title="$.scrollTo( '#excel-table', 1800, {easing:'elasout'} );" href="#excel-table" >School Directory</a></li>
          </ul>          
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
    <div id="school" style="margin-top:40px;">
    
      {% if form.errors %}
                        {% for error in form.non_field_errors %}
                            <p>{{error}}</p>
                        {% endfor %}
      {% endif %}
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <form class="form-horizontal" id="school_form" role="form" action="/" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% load app_tags %}
            {% for f in form %}
             {% if f.label == "Other Language" %}
                 <div class="form-group" id="language" style="display: none;">
             {% else %}
                 <div class="form-group">
             {% endif %}
                    <label for="{{f.label}}" class="col-sm-2 control-label">{{f.label}}</label>
                    <div class="col-sm-10">
                        {{ f|placeholder:f.label }}
                    </div>
                
            </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-lg btn-primary" type="submit">Save</button>
                </div>
            </div>
        </form>        
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.0/js/jquery.dataTables.js"></script>
    <script src="http://jquery-datatables-column-filter.googlecode.com/svn/trunk/media/js/jquery.dataTables.columnFilter.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
    <script type="text/javascript" src="http://demos.flesler.com/jquery/scrollTo/js/jquery.scrollTo-min.js?1.4.11"></script>
    <script type="text/javascript">
        $(document).ready ( function(){
            var lat, lng;
            //$("#map-canvas").hide();
            navigator.geolocation.getCurrentPosition(function(position)
            { 
                lat = position.coords.latitude;
                lng = position.coords.longitude;
                console.log( lat + ":" + lng);
                $("input#id_latitude").val(lat);
                $("input#id_longitude").val(lng);
            });
            
            
            $("#school_form").validate({
                rules: {
                    name: {
                        required: true,
                        minlength: 2,
                        maxlength: 200                      
                    },
                    min_fee: {
                        required: true,
                        min: 0,                                             
                    },
                    max_fee: {
                        required: true,
                        min: 0,                                             
                    },
                    establishment: {
                        required: true,
                        minlength: 4,
                        maxlength: 4,
                        min: 1800                       
                    },
                    
                    lowest_class: "required",
                    highest_class: "required",
                    recognized: "required",
                    management_type: "required",
                    medium_of_instruction : "required",
                    street_address_1: "required",
                    street_address_2: "required",
                    city: "required",
                    state: "required",
                    pincode: {
                        required: true,
                        minlength: 6,
                        maxlength: 6                    
                    }
                },
                messages: {
                    name: {
                        required: 'Name is required',
                        minlength: 'Min allowed length for name is 2 chars',
                        maxlength: 'Max allowed length for name is 200 chars'                   
                    },
                    min_fee: {
                        required: 'Minimum Monthly Fee is required',
                        min: 'Minimum Value is zero',                                               
                    },
                    max_fee: {
                        required: 'Maximum Monthly Fee is required',
                        min: 'Minimum Value is zero',                                               
                    },
                    establishment: {
                        required: 'Year of establishment is required',
                        minlength: 'Should be only 4 characters',
                        maxlength: 'Should be only 4 characters',
                        min: 'Year should be greater than 1800'                     
                    },
                    recognition: {
                        minlength: 'Should be only 4 characters',
                        maxlength: 'Should be only 4 characters',
                        min: 'Year should be greater than 1800'                         
                    },
                    lowest_class: "Enter Lowest Class",
                    highest_class: "Enter Highest Class",
                    recognized: "Enter Recognized",
                    management_type: "Enter Management Type",
                    medium_of_instruction : "Enter Medium of instructions",
                    street_address_1: "Enter Street Address Line 1",
                    street_address_2: "Enter Street Address Line 2",
                    city: "Enter Street City",
                    state: "Enter State",
                    recognition: {
                        required: 'Pincode is required',
                        minlength: 'Should be only 6 characters',
                        maxlength: 'Should be only 6 characters'                        
                    }
                },
                highlight: function(element, errorClass, validClass) {
                    $(element)
                        .parent('div')
                        .parent('div')
                        .addClass("has-error");

                },
                unhighlight: function(element, errorClass, validClass) {
                    $(element)
                        .parent('div')
                        .parent('div')
                        .removeClass("has-error");

                },
            });
            
            $("#id_medium_of_instruction").change(function() {
                if($("#id_medium_of_instruction").val() == "Other")
                    {
                       $("#language").show();          
                       $('#id_other_language').attr('placeholder','Please Specify Here');
                    }
                else{
                    $("#language").hide();
                }
                });
            
            
            $("#add-school").click ( function() {
                jQuery(this).parent('li').addClass('active');
                jQuery("#project").parent('li').removeClass('active');
            });
            $("#project").click ( function() {
                jQuery(this).parent('li').addClass('active');
                jQuery("#add-school").parent('li').removeClass('active');
            });
            $('#example').dataTable( {
                "ajax": "excel/"
            } ).columnFilter({sPlaceHolder: "head:before",
            aoColumns:[
                { sSelector: "#schoolName"  },
                { sSelector: "#lowerclass"  },
                { sSelector: "#higherclass"  },
                { sSelector: "#address" },
                { sSelector: "#pincode" },
                { sSelector: "#medium"  },
                { sSelector: "#recognition", type:"select", values : ["recognised", "unrecognized"] },
                { sSelector: "#management" },
                { sSelector: "#cost" }
                ]
            }); 
            
        });

    </script>
    
    
  </body>
</html>

school_data/templates/map.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>KML feature details</title>
    <style>
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>
function initialize() {
  var mapOptions = {
    zoom: 12
  };

  var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  var kmlLayer = new google.maps.KmlLayer({
    url: 'http:\/\/indiai.org\/data\/india_institute_patna_school_gis_map.kml',
    map: map
  });

}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
  </head>
  <body>
    <div id="map-canvas" style="width:100%; height:100%; float:left"></div>
    <div id="content-window" style="width:19%; height:100%; float:left"></div>
  </body>
</html>